[package]
name = "web-app"
version = "0.1.0"
authors = ["Anatol Ulrich <anatol@versteht.es>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trenchcoat = { path = "..", features = ["compiler"]}
chrono = { version = "0.4", features=["wasmbind"] }
fermi = "0.2"
gloo =  { version = "0.8", features = ["futures"] }


dioxus = { version = "0.2.4", features = ["web"] }

log = "0.4.6"

# WebAssembly Debug
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
