[application]

# App (Project) Name
name = "trenchcoat-web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "none"

[web.app]

# HTML title tag content
title = "trenchcoat"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public", "../src"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["style.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
